source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftExtension_Example', :exclusive => true do
  pod 'SwiftExtension', :path => '../'
end

target 'SwiftExtension_Tests', :exclusive => true do
  pod 'SwiftExtension', :path => '../'

  
end
