source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftExtension_Example' do
  pod 'SwiftExtension', :path => '../'
end

target 'SwiftExtension_Tests' do
  pod 'SwiftExtension', :path => '../'

  
end
